# Generated by Django 4.0.5 on 2022-06-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0002_characteristics_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristics',
            name='animal',
        ),
        migrations.AddField(
            model_name='characteristics',
            name='animal',
            field=models.ManyToManyField(related_name='characteristics', to='characteristics.characteristics'),
        ),
    ]
