# Generated by Django 4.0.5 on 2022-06-20 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0003_remove_characteristics_animal_characteristics_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='scientific_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
