# Generated by Django 4.0.5 on 2022-06-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0005_remove_characteristics_scientific_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristics',
            name='animal',
        ),
    ]
