# Generated by Django 4.0.5 on 2022-06-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_remove_animal_characteristics'),
        ('characteristics', '0006_remove_characteristics_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='animal',
            field=models.ManyToManyField(related_name='animals', to='animals.animal'),
        ),
    ]
