# Generated by Django 4.0.5 on 2022-06-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_remove_animal_characteristics'),
        ('characteristics', '0008_alter_characteristics_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='animal',
            field=models.ManyToManyField(related_name='characteristic', to='animals.animal'),
        ),
    ]
