# Generated by Django 4.0.5 on 2022-06-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0009_alter_characteristics_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristics',
            name='animal',
        ),
    ]
