# Generated by Django 4.0.5 on 2022-06-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_animal_characteristic_animal_group'),
        ('characteristics', '0010_remove_characteristics_animal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Characteristics',
            new_name='Characteristic',
        ),
    ]
