# Generated by Django 4.0.5 on 2022-06-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0006_remove_characteristics_animal'),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='characteristics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='group',
            field=models.ManyToManyField(related_name='characteristics', to='characteristics.characteristics'),
        ),
    ]
