# Generated by Django 4.0.5 on 2022-06-20 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_group_animal'),
        ('characteristics', '0006_remove_characteristics_animal'),
        ('animals', '0002_animal_characteristics_animal_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='animal',
            name='characteristics',
            field=models.ManyToManyField(related_name='characteristics', to='characteristics.characteristics'),
        ),
        migrations.RemoveField(
            model_name='animal',
            name='group',
        ),
        migrations.AddField(
            model_name='animal',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='groups.group'),
        ),
    ]
