# Generated by Django 4.0.5 on 2022-06-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_remove_animal_characteristics_animal_characteristics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='group',
        ),
    ]
