# Generated by Django 4.0.5 on 2022-06-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_remove_animal_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='characteristics',
        ),
    ]
