# Generated by Django 4.0.5 on 2022-06-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_rename_characteristic_animal_characteristics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='group',
            new_name='group_id',
        ),
    ]
