# Generated by Django 4.0.5 on 2022-06-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_rename_group_animal_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='group_id',
            new_name='group',
        ),
    ]
