# Generated by Django 4.0.5 on 2022-06-21 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_remove_animal_characteristics'),
        ('groups', '0005_alter_group_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='animals.animal'),
        ),
    ]
